export const NAV_LINKS = [
  { href: "/corso", label: "Corso" },
  { href: "/teoria", label: "Teoria" },
  { href: "/applicazioni", label: "Applicazioni" },
  { href: "/casi", label: "Case study" },
  { href: "/attuario", label: "Attuari" },
  { href: "/chi-siamo", label: "Chi siamo" },
  { href: "/risorse", label: "Risorse" },
  { href: "/community", label: "Community" },
  { href: "/wiki", label: "Wiki" },
  { href: "/notizie", label: "Notizie" },
  { href: "/strumenti", label: "Strumenti" },
  { href: "/shop", label: "Shop" },
  { href: "/blog", label: "Blog" },
];
